General:
  # Kick connecting players if the server encounters an error
  KickConnectionError: true
  # Allow anyone who has been /op'ed to bypass all permission checks
  # (effectively making them have the same control as console)
  OpsBypassPermissions: false
  # How much time to wait until reports expire (Default is 3d)
  ReportExpiry: 3d
  # The translation file you wish to use. (Default: messages.en_us.yml)
  TranslationFile: "messages.en_us.yml"

database:
  host: localhost
  port: 3306
  name: mcdb
  username: mc
  password: dbpw
  # Maximum number of times mysql will try to reconnect before giving up.
  MaxReconnects: 5
  # Number of times to check for expired temp bans
  # Currently set to 30 seconds
  # It's best to leave this alone unless you know what you
  # are doing with it.
  QueryUpdate: 30

Discord:
  Enabled: false
  Webhook: https://discordapp.com/api/webhooks/xxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ReportWebhook: https://discordapp.com/api/webhooks/xxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # Example: Justasic banned NotZachery for abusing villagers [SILENT] [#BF7BD5C85]
  UseSimplifiedMessage: false
  WebhookProfilePicture: "https://notzachery.github.io/images/joy.png"

BanSettings:
  # Prevents over-reaching bans 
  insane:
    # Allow bans with insane ipmasks (over-reaching IP/CIDR bans)
    ipmasks: false

    # Allow bans with insane regex (over-reaching regular expressions)
    regex: false

    # What percentage of players on the server to trigger
    # specifying an insane ban as. The default is 75.5%
    # which means if you have 100 players on the server
    # the ban will not be allowed if it will be banning
    # 75 or more players.
    trigger: 75.5

WarningSettings:
  # Spawns a box around the player
  SpawnBox: true
  BoxMaterial: Barrier
  FreezePlayer: true
  # This will just send a chat message saying they've been warned.
  SimpleWarning: false

FreezeSettings:
  # Spawns a box around the player
  SpawnBox: true
  BoxMaterial: Barrier
  FreezePlayer: true

IPBanSettings:
  # Optionally specify how wide reaching the ban will go
  InsanePercentage: 90

ReportSettings:
  # List of report types that are valid for the report command.
  Types:
    - Cheating
    - Game
    - Griefing
    - Hacking
    - Spamming
    - Profanity
    - Racism
    - Scamming
    - Advertisement
    - Other

# Draw a box around the ban message!
# WARNING! If their window is smaller than the box length, it will text-wrap
# Removed due to how minecraft handles whitespace.................
# BanMessageBox: false
