General:
  # Kick connecting players if the server encounters an error
  KickConnectionError: true

database:
  host: localhost
  port: 3306
  name: mcdb
  username: mc
  password: dbpw
  # Maximum number of times mysql will try to reconnect before giving up.
  MaxReconnects: 5
  # Number of times to check for expired temp bans
  # Currently set to 30 seconds
  # It's best to leave this alone unless you know what you
  # are doing with it.
  QueryUpdate: 30

Discord:
  Webhook: https://discordapp.com/api/webhooks/645266026694574097/UCUHIg3jfnd5Y8C58Csl2sEVMwn4x-NpWB2xiOlKNbzKI-SBvqXixJWKLyJyZEVP0icp
  # Example: mod banned iZachery for abusing villagers [SILENT] [#B-BF7BD5C85]
  UseSimplifiedMessage: false
  WebhookProfilePicture: "https://i.imgur.com/mKRAesS.png"

WarningSettings:
  # Spawns a box around the player
  SpawnBox: true
  BoxMaterial: Barrier
  FreezePlayer: true
  # This will just send a chat message saying they've been warned.
  SimpleWarning: false

FreezeSettings:
  # Spawns a box around the player
  SpawnBox: true
  BoxMaterial: Barrier
  FreezePlayer: true

# Draw a box around the ban message!
# WARNING! If their window is smaller than the box length, it will text-wrap
# Removed due to how minecraft handles whitespace.................
# BanMessageBox: false
