name: LolBans
version: ${project.version}
main: com.ristexsoftware.lolbans.Main
api-version: 1.13
authors: [Zachery Coleman, Justasic]
description: A ban system for minecraft, nothing fancy
permission-message: &noperms "§cError: §fAccess Denied!"
website: https://github.com/notzachery
commands:
  ban:
    description: Ban a player
  staffrollback:
    description: Rollback a staff member's actions
  staffhistory:
    descripton: Show staff history
  ipban:
    description: Ban an ip address or CIDR range
  regexban:
    description: Ban a username/hostname/ip address based on a Regular Expression
  kick:
    description: Ban a player
  mute:
    description: mute a player
  unban:
    description: Unban a payer
  mutechat:
    description: Mute the chat for all players (togglable)
  unmute:
    description: Unban a payer
  history:
    description: Get history of users punishments
    aliases: [h]
  clearhistory:
    description: Clear history of a player
    aliases: [ch]
  banwave:
    description: add user to the banwave
  warn:
    description: Warn a player
  accept:
    description: accept a warning
  broadcast:
    description: Broadcast a message to all online players
  report:
    description: Report a user
