name: LolBans
version: ${project.version}
main: me.zacherycoleman.lolbans.Main
api-version: 1.13
authors: [Zachery Coleman, Justasic]
description: A ban system for minecraft, nothing fancy
permission-message: &noperms "§cError: §fAccess Denied!"
website: https://github.com/notzachery
commands:
  ban:
    description: Ban a player
    usage: |
          Syntax Error!
          Use /ban <player> <ban time|*> <reason>
  kick:
    description: Ban a player
    usage: |
          Syntax Error!
          Use /kick <player> <reason>
  mute:
    description: mute a player
    usage: |
          Syntax Error!
          Use /mute <player> <mute time|*> <reason>
  unban:
    description: Unban a payer
    usage: |
        Syntax Error!
        Use /unban <player> <reason>
  mutechat:
    description: Mute the chat for all players (togglable)
    usage: |
        Syntax Error!
        Use /mutechat
  unmute:
    description: Unban a payer
    usage: |
        Syntax Error!
        Use /unmute <player> <reason>
  history:
    description: Get history of users punishments
    usage: |
        Syntax Error!
        Use /history <player>
    aliases: [h]
  clearhistory:
    description: Clear history of a player
    usage: |
        Syntax Error!
        Use /clearhistory <player>
    aliases: [ch]
  banwave:
    description: add user to the banwave
    usage: |
        Syntax Error!
        Use /banwave <add|remove|enforce> [player]
  warn:
    description: Warn a player
    usage: |
        Syntax Error!
        Use /warn <player> [-s] <reason>
  accept:
    description: accept a warning
